"""empty message

Revision ID: 656a27e515d3
Revises: 1580dfa63a1f
Create Date: 2021-11-07 11:56:57.855650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656a27e515d3'
down_revision = '1580dfa63a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_genres',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'genre_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books_genres')
    # ### end Alembic commands ###
